-- 07/03/2024 Seminar 3

-- SET SERVEROUTPUT ON

DECLARE
    VSTRING VARCHAR(100) DEFAULT 'ANA, AI PORTOCALE SI BANANE??? NU AM!!!';
    VVOWELS VARCHAR(100);
    VCONSONANTS VARCHAR(100);
    VOTHERCHARACTERS VARCHAR(100);
    LETTER CHAR;
    I PLS_INTEGER DEFAULT 1;
    
BEGIN
    FOR I IN REVERSE 1..100 LOOP -- REVERSE IS THE ONLY MODIFIER AVAILABLE TO THE LOOP
        -- I:=I+2; -- `I` CANNOT BE MODIFIED INSIDE THE LOOP
        -- DBMS_OUTPUT.PUT_LINE(I); -- `I` CAN BE ACCESSED AND DISPLAYED
        NULL;
    END LOOP;

    -- EXAMPLE: EXTRACTING LETTERS FROM STRINGS (FOR LOOP)
    FOR I IN 1..LENGTH(VSTRING) LOOP
        LETTER := SUBSTR(UPPER(VSTRING), I, 1);
        
        IF LETTER NOT BETWEEN 'A' AND 'Z' THEN
            VOTHERCHARACTERS := VOTHERCHARACTERS||LETTER;
            
        ELSIF LETTER IN ('A', 'E', 'I', 'O', 'U') THEN
            VVOWELS := VVOWELS||LETTER;
            
        ELSE
            VCONSONANTS := VCONSONANTS||LETTER;
            
        END IF;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('STRING: '||VSTRING);
    DBMS_OUTPUT.PUT_LINE('VOWELS: '||VVOWELS);
    DBMS_OUTPUT.PUT_LINE('CONSONANTS: '||VCONSONANTS);
    DBMS_OUTPUT.PUT_LINE('OTHERS: '||VOTHERCHARACTERS);
    
END;
/

DECLARE
    VSTRING VARCHAR(100) DEFAULT 'ANA ARE MERE, CASTANE, PRUNE, BANANE!?';
    VVOWELS VARCHAR(100);
    VCONSONANTS VARCHAR(100);
    VOTHERCHARACTERS VARCHAR(100);
    LETTER CHAR;
    I PLS_INTEGER DEFAULT 1;
    
BEGIN
    -- EXAMPLE: EXTRACTING LETTERS FROM STRINGS (WHILE LOOP)
    WHILE(I <= LENGTH(VSTRING)) LOOP
        LETTER := SUBSTR(UPPER(VSTRING), I, 1);
        
        IF LETTER NOT BETWEEN 'A' AND 'Z' THEN
            VOTHERCHARACTERS := VOTHERCHARACTERS||LETTER;
            
        ELSIF LETTER IN ('A', 'E', 'I', 'O', 'U') THEN
            VVOWELS := VVOWELS||LETTER;
            
        ELSE
            VCONSONANTS := VCONSONANTS||LETTER;
            
        END IF;
        
        I := I + 1;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('STRING: '||VSTRING);
    DBMS_OUTPUT.PUT_LINE('VOWELS: '||VVOWELS);
    DBMS_OUTPUT.PUT_LINE('CONSONANTS: '||VCONSONANTS);
    DBMS_OUTPUT.PUT_LINE('OTHERS: '||VOTHERCHARACTERS);
END;
/

DECLARE
    VSTRING VARCHAR(100) DEFAULT 'URSUL MANINCA MURE DIN PADURE!!! 100% NATURALE';
    VVOWELS VARCHAR(100);
    VCONSONANTS VARCHAR(100);
    VOTHERCHARACTERS VARCHAR(100);
    LETTER CHAR;
    I PLS_INTEGER DEFAULT 1;
    
BEGIN
    -- EXAMPLE: EXTRACTING LETTERS FROM STRINGS (LOOP)
    LOOP
        LETTER := SUBSTR(UPPER(VSTRING), I, 1);
        
        IF LETTER NOT BETWEEN 'A' AND 'Z' THEN
            VOTHERCHARACTERS := VOTHERCHARACTERS||LETTER;
            
        ELSIF LETTER IN ('A', 'E', 'I', 'O', 'U') THEN
            VVOWELS := VVOWELS||LETTER;
            
        ELSE
            VCONSONANTS := VCONSONANTS||LETTER;
            
        END IF;
        
        EXIT WHEN (I = LENGTH(VSTRING)); -- `EXIT WHEN` CONDITION ON SIMPLE LOOPS
        
        I := I + 1;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('STRING: '||VSTRING);
    DBMS_OUTPUT.PUT_LINE('VOWELS: '||VVOWELS);
    DBMS_OUTPUT.PUT_LINE('CONSONANTS: '||VCONSONANTS);
    DBMS_OUTPUT.PUT_LINE('OTHERS: '||VOTHERCHARACTERS);
END;
/

-- USING A PL/SQL BLOCK DISPLAY THE EMPLOYEES FROM DEPARTMENTS 30 AND 50
DECLARE
    VFIRSTNAME EMPLOYEES.FIRST_NAME%TYPE;
    VLASTNAME EMPLOYEES.LAST_NAME%TYPE;
    
    VNUMRECORDS PLS_INTEGER;
    
    VMAX PLS_INTEGER;
    VMIN PLS_INTEGER;
BEGIN
    SELECT 
        COUNT(EMPLOYEE_ID) 
    INTO
        VNUMRECORDS 
    FROM
        EMPLOYEES
    WHERE
        DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 50;
    
    DBMS_OUTPUT.PUT_LINE(VNUMRECORDS||' EMPLOYEES WORK IN DEPARTEMENTS 30 AND 50');
    
--    FOR I IN 1..VNUMRECORDS LOOP
--        NULL;
--    END LOOP;
    
    SELECT
        MAX(EMPLOYEE_ID), MIN(EMPLOYEE_ID)
    INTO
        VMAX, VMIN
    FROM
        EMPLOYEES;
    
    FOR I IN VMIN..VMAX LOOP
        BEGIN -- NESTED BLOCK
            SELECT
                FIRST_NAME, LAST_NAME
            INTO
                VFIRSTNAME, VLASTNAME
            FROM
                EMPLOYEES
            WHERE
                EMPLOYEE_ID = I;
                
            DBMS_OUTPUT.PUT_LINE(VFIRSTNAME||' '||VLASTNAME);
            
            EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
        END;
    END LOOP;
    
    -- 
END;
/

-- EXERCISE USING COLLECTION
DECLARE
    TYPE T_VAL IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;    
    V T_VAL;
BEGIN
    SELECT FIRST_NAME||' '||LAST_NAME AS DD BULK COLLECT INTO V FROM EMPLOYEES WHERE DEPARTMENT_ID IN (30, 50) ORDER BY EMPLOYEE_ID;
    
    FOR I IN V.FIRST..V.LAST LOOP
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;
    
    -- 
END;
/

